---
title: Economía Política
subtitle: Examen Final - 28 de noviembre de 2022
author: |
  | División: Freille
  | Licenciatura en Economía
  | FCE-UNC

output: pdf_document
fontsize: 12pt
geometry: legalpaper,margin=1.1in
header-includes:
  - \usepackage{amsmath}
  - \usepackage{tcolorbox}
  - \newtcolorbox{myquote}{colback=cyan!35!white, colframe=cyan!85!black}
  - \renewenvironment{quote}{\begin{myquote}}{\end{myquote}}
---

# **Multiple Choice [28 pts]**

| **1** 	| **2** 	| **3** 	| **4** 	| **5** 	| **6** 	| **7** 	| **8** 	|
|-------	|-------	|-------	|-------	|-------	|-------	|-------	|-------	|
|       	|       	|       	|       	|       	|       	|       	|       	|


1. Cuál de la/s siguiente/s es FALSA:
    a. cuando no hay heterogeneidad en preferencias, el problema se reduce a un problema técnico;
    b. cuando hay heterogeneidad en preferencias exante, el problema se reduce a como se ponderan las utilidades individuales;
    c. cuando hay heterogeneidad en preferencias expost, el problema se reduce a como se ponderan las utilidad individuales;
    d. cuando hay heterogeneidad en preferencias expost, el problema se reduce tanto a como se ponderan las utilidades individuales y a como se distribuyen las participaciones en las cantidades consumidas;
    e. ninguna de las anteriores

2. Sea $V_{m}(q)$ las preferencias del votante mediano, en el modelo de competencia electoral downsiano la probabilidad de que el votante mediano vote por el partido A será:
    a. igual a 0 si $V_{m}(q_{A}) > V_{m}(q_{B})$
    b. igual a 0 si $V_{m}(q_{A}) < V_{m}(q_{B})$
    c. igual a 1 si $V_{m}(q_{A}) < V_{m}(q_{B})$
    d. igual a 1/2 si $V_{m}(q_{A}) > V_{m}(q_{B})$
    e. igual a 1 si $V_{m}(q_{A}) > V_{m}(q_{B})$
    f. las alternativas $b$ y $d$ son correctas
    g. las alternativas $b$ y $c$ son correctas
    h. las alternativas $b$ y $e$ son correctas
    i. las alternativas $c$ y $e$ son correctas
    j. ninguna es correcta

3. En el modelo básico de medios y políticas [Stromberg (2001)], cuál de las siguientes es FALSA:
    a. redistribución es mayor para programas de gasto que son intensivamente cubiertos por los medios
    b. mientras más informados los contribuyentes, menores serán las rentas para el político
    c. una mayor provisión de noticias por parte de los medios está asociado  inequivocamente a mayores impuestos
    d. el nivel de rentas políticas en un modelo con medios será siempre mayor que con un planificador social benevolente
    e. el gsato en equilibrio del programa es creciente en el número de gente informada
    f. ninguna es correcta

4. En el marco de la discusión de lobbies y competencia electoral, cuál de los siguientes es VERDADERA:
    a. en el caso de políticas particularistas, las contribuciones son sólo función de la política del candidato que favorece a ese GIS, $C_{i}=f(q_{a})$
    b. en el caso de políticas colectivas, las contribuciones son sólo función de la política del candidato que favorece a ese GIS, $$C_{i}=f(q_{a})$
    c. la probabilidad de ganar es menor para el partido alineado con el GIS que más valua las políticas particularistas
    d. si existe financiamiento público, resultará en políticas particularistas más alejadas del mediano
    e. si la proporción de votantes no informados aumenta, las políticas de equilibrio divergen
    f. las alternativas $a$ y $c$ son correctas
    g. las alternativas $b$ y $e$ son correctas
    h. las alternativas $a$ y $e$ son correctas
    i. las alternativas $a$, $d$ y $e$ son correctas
    
5. Dados 6 grupos de individuos con los siguientes ordenamientos de preferencias sobre 5 alternativas: 
G1 (18 personas) 	A > D > E > C > B
G2 (12 personas)	B > E > D > C > A
G3 (10 personas) 	C > B > E > D > A
G4 (9 personas)		D > C > E > B > A
G5 (4 personas)		E > B > D > C > A
G6 (2 personas) 	E > C > D > B > A
¿Cuál será la ganadora por el método de Condorcet?
    a. A
    b. B
    c. C
    d. D
    e. E
    f. No hay ganador de Condorcet
    g. No puede saberse con certeza con la información suministrada

6. Una elección debe ser decidida en base al método de la cuenta de Borda. Hay 5 (cinco) candidatas -A, B, C, D y E- y 40 (cuarenta) votantes. Si el candidato A obtiene 139 puntos, el candidato B obtiene 121 puntos, el candidato C obtiente 80 puntos, y el candidato D obtiene 113 puntos, quién será el ganador de la elección:
    a. A
    b. B
    c. C
    d. D
    e. E
    f. Hay un empate entre A y E
    g. No puede saberse con certeza con la información suministrada


7. En el modelo de democratización de Acemoglu y Robinson si $\theta > \mu$, entonces
    a. En estado $S=L$, puede haber revolución
    b. En estado $S=H$, nunca hay revolución
    c. En estado $S=H$, sólo hay revolución cuando la misma es excesivamente costosa ($\mu$ alto)
    d. En estado $S=L$, sólo hay revolución cuando la misma es relativamente barata ($\mu$ bajo)
    e. En estado $S=H$, sólo hay revolución cuando la misma es relativamente barata ($\mu$ bajo).
    f. Ninguna es correcta

8. En el paper de Olken and Barron (2009) sobre peajes en rutas de Indonesia, cuál/es eran VERDADERAS
    a. Las coimas pagadas representan, en relación al costo total del viaje, menos que el salario de los conductores
    b. Mientras más agentes en los puestos de peaje, menores las coimas pagadas
    c. El monto de la coima solía ser mayor mientras más cerca del final del trayecto se encontraba el peaje
    d. Los camiones con mayor peso y mayor valor de mecadería tendían a pagar menos coimas
    e. Los puestos de peaje que tenían agentes con armas tendían a evidenciar mayores coimas
    f. Ninguna es correcta


    
# **Verdadero-Falso [16 pts]** - No requiere justificación

1. [   ] En casos de corrupción con robo, el precio bruto cobrado al consumidor es siempre mayor que el que regiría en casos de corrupción sin robo
2. [   ] El número de coaliciones de mayoría ganadoras posibles es inversamente proporcional a la distancia existente entre la posición mediana y la posición rival
3. [   ] En el modelo de no democracia de Acemoglu y Robinson, si THETA es mayor a MU, entonces en todos los escenarios posibles no habrá nunca revolución
4. [   ] El *payoff* de saquear una economía es mayor  que el de extraer recursos democráticamente tanto a corto como largo plazo
5. [   ] Según el modelo de Baron mientras mayor sea la proporción de votantes no informados, $k$, mayor será la tendencia centrífuga en posiciones/anuncios de política
6. [   ] Si todas las preferencias de un conjunto de 3 (tres) individuos son de pico único, necesariamente también serán de cruce único
7. [   ] En el modelo de medios y política el nivel de rentas políticas endógenas es siempre mayor al que rige con un planificador social benevolente
8. [   ] Las instituciones políticas determinan la distribución del poder *de facto*


# **Ejercicios [22.5 pts]**

1. [12.5 pts] Un total 19 electores votan por 5 candidatos con la siguiente tabla de preferencias

| # votos 	| 9 	| 6 	| 4 	|
|---------	|---	|---	|---	|
| 1er ord 	| B 	| D 	| C 	|
| 2do ord 	| E 	| C 	| B 	|
| 3er ord 	| A 	| A 	| E 	|
| 4to ord 	| C 	| B 	| D 	|
| 5to ord 	| D 	| E 	| A 	|

  - Se le pide:
    1. ¿Cuál, si existiera, ganaría bajo pluralidad?
    2. ¿Cuál, si existiera, ganaría bajo regla de Borda?
    3. ¿Cuál, si existiera, ganaría bajo metódo de mayoría con votaciones de a pares?
    4. Suponga ahora que la anterior elección es declarada fraudulenta. Como consecuencia de esto, el candidato D se baja de la elección. Se hace una nueva elección con las mismas preferencias de la tabla anterior pero ahora con sólo 4 alternativas. Responda a los incisos (a), (b) y (c) de nuevo. 


2. [5 pts] La suma de todos los puntajes de Borda en una elección es 45+56+52+27=180. Explique por qué la suma de todos los puntajes de Borda es igual a 180 en *cualquier* elección que involucre 18 votantes y 4 cuatro candidatos independientemente de los perfiles de preferencias. ¿Cuál sería la suma de los puntajes de Borda en una elección involucrando 20 votantes y 3 candidatos? Explique, ilustre y fundamente en ambas respuestas. 

3. [5 pts] Suponga los siguientes perfiles de preferencias y que la elección debe ser resuelta por la cuenta de Borda con la convención de que los empates son resueltos *alfabéticamente*. Además suponga que uno de los dos votantes cuyo ranking es $B \succ A \succ C$ vota deshonestamente $A \succ B \succ C$. Se le pide que **muestre** que esto cambiará el resultado de la elección en una manera que el votante deshonesto prefiere

| **3** 	| **2** 	| **3** 	|
|-------	|-------	|-------	|
| C     	| B     	| A     	|
| B     	| A     	| C     	|
| A     	| C     	| B     	|


# **Ensayos [33.5 pts]**

1. [12.5 pts] *La muerte del teorema del votante mediano: Cuando las elecciones son decididas por el surgimiento de aquellos que habitualmente no votan, muchos de los supuestos del teorema del votante mediano pierden sentido*, escribió Jon Fraenken, profesor de política comparada al analizar las dos últimas elecciones presidenciales en EEUU. Explique, justifique y argumente si (y porqué) está de acuerdo con el enunciado. Argumente qué otro modelo de competencia electoral podría tratar mejor los problemas que menciona el autor.

2. [12.5 pts] En una situación en que se parte de no democracia, explique e ilustre con ejemplos bajo qué circunstancias y condiciones serán más proclives las elites a conceder derechos políticos (democracia y voto) y alternativamente bajo qué circunstancias y condiciones no estarán dispuestas a hacerlo tratando de ofrecer otras opciones (¿cuáles) que eviten conceder la decisión sobre tributos y gastos al mediano del electorado?

3. [8.5 pts] Explique la diferencia entre políticas particularistas y políticas colectivas en relación con los diferentes incentivos a activar contribuciones de campaña de uno o más de un lobby. De ejemplos de tales políticas y de cómo generarían en la práctica incentivos a diferentes lobbies a contribuir o no. 


