---
title: Economía Política
subtitle: Examen Final - 03 de marzo de 2023
author: |
  | División: Freille
  | Licenciatura en Economía
  | FCE-UNC

output: pdf_document
fontsize: 12pt
geometry: legalpaper,margin=1.1in
header-includes:
  - \usepackage{amsmath}
  - \usepackage{tcolorbox}
  - \newtcolorbox{myquote}{colback=cyan!35!white, colframe=cyan!85!black}
  - \renewenvironment{quote}{\begin{myquote}}{\end{myquote}}
---

# **Multiple Choice [27 pts]**


| **1** | **2** | **3** | **4** | **5** | **6** | **7** | **8** | **9** | **10** |
|-------|-------|-------|-------|-------|-------|-------|-------|-------|--------|
|       |       |       |       |       |       |       |       |       |        |

1. Hay 33 votantes que tienen que elegir una alternativa usando la cuenta de Borda (método n=1) con las siguientes preferencias. Si todos siguen sus preferencias, gana C. ¿Cuántos de los 7 votantes cuya favorita es A deberían cambiar sus órdenes de preferencia para que B resulte ganadora?

    | 7 	| 13 	| 10 	| 3 	|
    |---	|----	|----	|---	|
    | A 	| B  	| C  	| C 	|
    | C 	| C  	| A  	| B 	|
    | B 	| A  	| B  	| A 	|
    a. Al menos 2
    b. Al menos 4
    c. Todos los 7
    d. No importa cuántos cambien, C seguirá ganando

2. Sea $V_{m}(q)$ las preferencias del votante mediano, en el modelo de competencia electoral downsiano la probabilidad de que el votante mediano vote por el partido A será:
    a. igual a 0 si $V_{m}(q_{A}) > V_{m}(q_{B})$
    b. igual a 0 si $V_{m}(q_{A}) < V_{m}(q_{B})$
    c. igual a 1 si $V_{m}(q_{A}) < V_{m}(q_{B})$
    d. igual a 1/2 si $V_{m}(q_{A}) > V_{m}(q_{B})$
    e. igual a 1 si $V_{m}(q_{A}) > V_{m}(q_{B})$
    f. las alternativas $b$ y $d$ son correctas
    g. las alternativas $b$ y $c$ son correctas
    h. las alternativas $b$ y $e$ son correctas
    i. las alternativas $c$ y $e$ son correctas
    j. ninguna es correcta

3. En el modelo básico de medios y políticas [Stromberg (2001)], cuál de las siguientes es FALSA:
    a. redistribución es mayor para programas de gasto que son intensivamente cubiertos por los medios
    b. mientras más informados los contribuyentes, menores serán las rentas para el político
    c. una mayor provisión de noticias por parte de los medios está asociado  inequivocamente a mayores impuestos
    d. el nivel de rentas políticas en un modelo con medios será siempre mayor que con un planificador social benevolente
    e. el gsato en equilibrio del programa es creciente en el número de gente informada
    f. ninguna es correcta

4. En el marco de la discusión de lobbies y competencia electoral, cuál de los siguientes es VERDADERA:
    a. en el caso de políticas particularistas, las contribuciones son sólo función de la política del candidato que favorece a ese GIS, $C_{i}=f(q_{a})$
    b. en el caso de políticas colectivas, las contribuciones son sólo función de la política del candidato que favorece a ese GIS, $$C_{i}=f(q_{a})$
    c. la probabilidad de ganar es menor para el partido alineado con el GIS que más valua las políticas particularistas
    d. si existe financiamiento público, resultará en políticas particularistas más alejadas del mediano
    e. si la proporción de votantes no informados aumenta, las políticas de equilibrio divergen
    f. las alternativas $a$ y $c$ son correctas
    g. las alternativas $b$ y $e$ son correctas
    h. las alternativas $a$ y $e$ son correctas
    i. las alternativas $a$, $d$ y $e$ son correctas
    
5. Una elección debe ser decidida en base al método de la cuenta de Borda. Hay 5 (cinco) candidatas -A, B, C, D y E- y 40 (cuarenta) votantes. Si el candidato A obtiene 139 puntos, el candidato B obtiene 121 puntos, el candidato C obtiente 80 puntos, y el candidato D obtiene 113 puntos, quién será el ganador de la elección:
    a. A
    b. B
    c. C
    d. D
    e. E
    f. Hay un empate entre A y E
    g. No puede saberse con certeza con la información suministrada


6. En el modelo de democratización de Acemoglu y Robinson si $\theta > \mu$, entonces
    a. En estado $S=L$, puede haber revolución
    b. En estado $S=H$, nunca hay revolución
    c. En estado $S=H$, sólo hay revolución cuando la misma es excesivamente costosa ($\mu$ alto)
    d. En estado $S=L$, sólo hay revolución cuando la misma es relativamente barata ($\mu$ bajo)
    e. En estado $S=H$, sólo hay revolución cuando la misma es relativamente barata ($\mu$ bajo).
    f. Ninguna es correcta

7. En el paper de Olken and Barron (2009) sobre peajes en rutas de Indonesia, cuál/es eran VERDADERAS
    a. Las coimas pagadas representan, en relación al costo total del viaje, menos que el salario de los conductores
    b. Mientras más agentes en los puestos de peaje, menores las coimas pagadas
    c. El monto de la coima solía ser mayor mientras más cerca del final del trayecto se encontraba el peaje
    d. Los camiones con mayor peso y mayor valor de mecadería tendían a pagar menos coimas
    e. Los puestos de peaje que tenían agentes con armas tendían a evidenciar mayores coimas
    f. Ninguna es correcta

8. Sean 6 partidos en una eleccion que obtienen las siguientes proporciones de votos: [0.47; 0.25; 0.08; 0.08; 0.08; 0.04]. El numero efectivo de partidos para esta elección será: [NOTA: Trabaje a 2 (dos) decimales sin redondear]
    a. 3.53
    b. 3.15
    c. 3.28
    d. 3.00
    e. 4.53
    f. No puede saberse con la información suministrada

9. ¿Cuál de las siguientes NO SON preferencias de pico único?
    a. $x \succ y \succ z \succ w$
    b. $z \succ y \succ x \succ w$
    c. $w \succ z \succ y \succ x$
    d. $w \succ x \succ y \succ z$
    e. $w \succ y \succ x \succ z$
    f. $y \succ z \succ x \succ w$
    g. $y \succ x \succ w \succ z$


    
# **Verdadero-Falso [20 pts]** - No requiere justificación

1. [   ] En casos de corrupción con robo, el precio bruto cobrado al consumidor es siempre mayor que el que regiría en casos de corrupción sin robo
2. [   ] El número de coaliciones de mayoría ganadoras posibles es inversamente proporcional a la distancia existente entre la posición mediana y la posición rival
3. [   ] En el modelo de no democracia de Acemoglu y Robinson, si THETA es mayor a MU, entonces en todos los escenarios posibles no habrá nunca revolución
4. [   ] El *payoff* de saquear una economía es mayor  que el de extraer recursos democráticamente tanto a corto como largo plazo
5. [   ] Los sistemas con distritos uninominales tienden a ser bipartidistas y suelen tener sistemas de votación por mayoría
6. [   ] Si todas las preferencias de un conjunto de 3 (tres) individuos son de pico único, necesariamente también serán de cruce único
7. [   ] En el modelo de medios y política el nivel de rentas políticas endógenas es siempre mayor al que rige con un planificador social benevolente
8. [   ] Las instituciones políticas determinan la distribución del poder *de facto*
9. [   ] Si las preferencias de un conjunto de individuos no satisfacen ni la condición de pico único ni la de cruce único, entonces no existirá nunca ganador de Condorcet
10. [   ] En el modelo más simple de redistribución (Meltzer & Richard) la alícuota de equilibrio preferida por el votante mediano será igual a 1 


# **Ejercicios [17 pts]**

1. [10 pts] Hay 2 (dos) agentes $\alpha_{i}$ y $\alpha_{j}$ y cuatro alternativas de política $q_1 < q_2 < q_3 < q_4$. Las preferencias de los votantes son>
\begin{align}
\alpha_{i}: q_2 \succ q_3 \succ q_4 \succ q_1 \\
\alpha_{j}: q_3 \succ q_2 \succ q_1 \succ q_4
\end{align}

donde $\succ$ significa "es preferido a". Se le pide:

a) Dibuje las curvas de utilidad para ambos agentes
b) Muestre que ambas tienen preferencias de pico único
c) Suponga que $\alpha_{i} < \alpha_{j}$. Muestre que las preferencias violan la propiedad de cruce único [NOTA: Compare el ranking de $q_1$ y $q_4$]
d) Suponga ahora que $\alpha_{j} < \alpha_{i}$. Muestra que aún así existe una violación de la propiedad de cruce único

2. [7 pts] En la premiación de los Oscars, hay 3 (tres) nominadas a mejor actor: Arthur Andrews (A), Bob Brown (B) y Clive Carter (C). La tabla de preferencias es:

| **123** | **101** | **442** | **212** | **315** |
|:-------:|:-------:|:-------:|:-------:|:-------:|
|    A    |    A    |    B    |    C    |    C    |
|    B    |    C    |    A    |    A    |    B    |
|    C    |    B    |    C    |    B    |    A    |

Se le pide:

a) ¿Cuántos actores votaron?
¿Cuántos votos de primera preferencia recibió cada nominado?
b) ¿Quién, si existe, ganaría bajo pluralidad?
c) ¿Quién, si existe, ganaría bajo mayoría?
d) ¿Existe ganador de Condorcet? ¿Cuál es?




# **Ensayos [36 pts]**

1. [12 pts] *La muerte del teorema del votante mediano: Cuando las elecciones son decididas por el surgimiento de aquellos que habitualmente no votan, muchos de los supuestos del teorema del votante mediano pierden sentido*, escribió Jon Fraenken, profesor de política comparada al analizar las dos últimas elecciones presidenciales en EEUU. Explique, justifique y argumente si (y porqué) está de acuerdo con el enunciado. Argumente qué otro modelo de competencia electoral podría tratar mejor los problemas que menciona el autor.

2. [12 pts] En una situación en que se parte de no democracia, explique e ilustre con ejemplos bajo qué circunstancias y condiciones serán más proclives las elites a conceder derechos políticos (democracia y voto) y alternativamente bajo qué circunstancias y condiciones no estarán dispuestas a hacerlo tratando de ofrecer otras opciones (¿cuáles) que eviten conceder la decisión sobre tributos y gastos al mediano del electorado?

3. [12 pts] Un analista argumentó lo siguiente: "El tipo de corrupción existente en este país hace prácticamente imposible que los agentes tengan incentivo a denunciarla por cuanto siempre se les exige pagar un precio mayor al que pagarían en ausencia de la misma". VERDADERO-FALSO. Justifique adecuadamente su respuesta y use instrumental gráfico/analítico. 


