---
title: "Adam Smith, liberal: nunca libertario"
subtitle: "Serie: A 250 años del libro *La Riqueza de las Naciones* de Adam Smith"
author: "Axel Kicillof"
format:
  pdf:
    documentclass: article
    papersize: a4
    fontsize: 11pt
    geometry:
      - margin=2.5cm
    toc: false
---

No todos lo saben, pero antes de desempeñarme como viceministro y ministro de Economía, diputado nacional y gobernador de la Provincia de Buenos Aires, me dediqué por más de 20 años a la investigación y a la docencia universitaria. Mi tesis de doctorado se centró en la Teoría general de Keynes, pero me especialicé también en otras dos áreas de investigación: el desarrollo de la economía argentina y la teoría económica desde una perspectiva histórica. De hecho, la editorial Siglo XXI acaba de lanzar una nueva edición de mi libro 'De Smith a Keynes. Siete lecciones de historia del pensamiento económico'. Las primeras dos de estas siete lecciones se ocupan de Adam Smith: algunas de las ideas que expongo a continuación provienen de ese libro.

Para comenzar a hablar de La riqueza de las naciones debo hacer una aclaración: no es posible analizar ninguna obra sin considerar la época en la que surgió. Recordemos entonces que, a fines del siglo XVIII, el régimen feudal se desmoronaba en gran parte de Europa y comenzaba a tomar impulso la llamada revolución industrial.

Smith se propuso caracterizar las leyes que gobernaban el nuevo régimen de producción cuando recién estaba naciendo. En las primeras palabras de su libro marca ya una ruptura con las escuelas de pensamiento anteriores –escolásticos, mercantilistas, fisiócratas–: "El trabajo anual de cada nación es el fondo que en principio provee de todas las cosas necesarias y convenientes para la vida, y que anualmente consume un país". En esta frase, en apariencia trivial, reside el núcleo conceptual –y la principal originalidad– de toda la obra. Para Adam Smith, la fuente de la riqueza no debe buscarse en la naturaleza, en la tierra, en el capital, en el dinero, en los metales preciosos como el oro o la plata, ni en el comercio, sino en el trabajo humano.

En la sociedad que él denomina "civilizada" se profundizó como nunca la división del trabajo, lo que trajo dos consecuencias: en primer lugar, el crecimiento exponencial, sin precedentes, de la productividad del trabajo. Con el famoso ejemplo de la fábrica de alfileres, Smith muestra que cada trabajador multiplicaba exponencialmente su capacidad productiva. Pero, en segundo lugar, Smith llega a una conclusión mucho más relevante desde el punto de vista teórico: "Tan pronto como se hubo establecido la división del trabajo, solo una pequeña parte de las necesidades de cada hombre se pudo satisfacer con el producto de su propia labor (...) El hombre vive así, gracias al cambio, convirtiéndose, en cierto modo, en mercader, y la sociedad misma prospera hasta ser lo que realmente es, una sociedad comercial". Esto no ocurría en las etapas históricas anteriores.

Si ahora cada individuo debe intercambiar el producto de su trabajo por el del trabajo ajeno, ¿cuáles son las leyes que gobiernan el intercambio de mercancías? O, dicho de otro modo, ¿cómo se determina el "valor" de los bienes? Como vimos, el origen de la riqueza es el trabajo humano. Por consiguiente, Smith intenta demostrar que la fuente del valor de cada mercancía es también el trabajo. En los primeros capítulos explica cómo opera esa "ley del valor" y también cómo se distribuye ese valor entre trabajadores, empresarios y propietarios de la tierra. Así, con sus avances, contradicciones, dificultades e interrogantes, Smith da origen, en buena medida, a las controversias que hasta el día de hoy distinguen a las escuelas de pensamiento.

Hay otra cuestión en la que Smith dejó una huella imborrable. Una vez disueltas las relaciones feudales de servidumbre y vasallaje, liberadas las restricciones y regulaciones de los gremios medievales, una vez convertidos en mercancías y en propiedad privada los productos, los instrumentos de trabajo y la tierra misma, ¿hacia dónde marchaba la sociedad? Numerosos autores de la época veían en la disolución de los lazos feudales y religiosos el riesgo de un verdadero caos (Blake lo llamó "el molino satánico"). Smith, en cambio, respondió a esta pregunta con dos planteos "revolucionarios". En primer lugar, no habría caos sino que reinaría un nuevo orden, no de origen divino pero tampoco gobernado por alguna autoridad, sino presidido por leyes económicas que actuarían de manera "inconsciente".

En segundo lugar, sostuvo que ese nuevo sistema aseguraba el crecimiento de la riqueza y que, además, su fruto se distribuiría entre todas las clases sociales: "La gran multiplicación de las producciones en todas las artes, originadas en la división del trabajo, da lugar, en una sociedad bien gobernada, a esa opulencia universal que se derrama hasta las clases inferiores del pueblo". Esta perspectiva optimista sobre el funcionamiento del capitalismo convirtió a Adam Smith, para muchos, no solo en el padre de la economía moderna sino también en el padre del liberalismo.

Ahora bien, en la cita anterior aparece una enigmática condición para alcanzar el bienestar: que la sociedad esté "bien gobernada". Por eso, buena parte del libro se dedica a aconsejar al "soberano" sobre qué hacer y qué no hacer en materia económica. En primer lugar, empleando la famosa metáfora de la "mano invisible" (que Smith utiliza una sola vez en toda la obra) asegura que, si "cualquier individuo pone todo su empeño en emplear su capital en sostener la industria doméstica y dirigirla a la consecución del producto que rinde más valor, resulta que cada uno de ellos colabora de una manera necesaria en la obtención del ingreso anual máximo para la sociedad". Es decir, el Soberano no debe interferir en las decisiones de inversión de los empresarios. Sin embargo, hay muchos aspectos en los que, según Smith, el Estado debe necesariamente actuar. Menciono a continuación solo algunos campos.

Para empezar, garantizar la defensa y la administración de justicia son obligaciones obvias –y primordiales– del Estado. Hasta aquí, seguramente, un liberal actual y hasta un libertario coincidirían. Pero Smith va mucho más allá. Por ejemplo, sostiene que "la defensa es mucho más importante que la opulencia", por lo que apoya las leyes de navegación que protegen al monopolio británico en el transporte marítimo. Fuera de este caso, condena el monopolio y recomienda limitarlo: "En el sistema del monopolio, el interés del consumidor es casi siempre sacrificado al del productor".

Para Smith, la educación es otra área en la que el gobierno tiene que intervenir pues temía que la división del trabajo, la repetición de tareas rutinarias y simples, embruteciera al trabajador. "Para este fin, el Estado puede facilitar la adquisición de esos elementos esenciales de la educación, estableciendo en cada parroquia o distrito una pequeña escuela donde los niños puedan ser enseñados por una tarifa tan moderada que incluso un trabajador común pueda pagarla." Para la época, se trata prácticamente de la defensa de la educación pública, universal y al alcance de todos.

Otro deber del soberano es encargarse de las obras públicas que "aunque sean en el más alto grado ventajosas para una gran sociedad, son, sin embargo, de tal naturaleza que la ganancia nunca podría compensar el gasto a cualquier individuo o pequeño número de individuos." Es lógico: en muchísimos casos no hay forma de que los individuos solventen la construcción de caminos, puentes, canales navegables y puertos, incluso cuando luego su mantenimiento pueda asegurarse a través de peajes.

En La riqueza de las naciones se condena la "usura" y se recomienda al gobierno que fije una tasa máxima para evitar los excesos que desviaban el capital de manos de productores hacia los especuladores: "En los países donde se permite el interés, la ley, para prevenir la extorsión de la usura, fija generalmente la tasa máxima que puede cobrarse sin incurrir en penalidades." En términos modernos, se trata de establecer regulaciones en el mercado de capitales.

En general, casi todas las escuelas y autores reconocen en Adam Smith al fundador de la economía moderna y, con matices, otorgan enorme relevancia y actualidad a sus aportes. Lo consideran un verdadero genio. Existe sin embargo una corriente que afirma todo lo contrario: la vertiente libertaria de la escuela austríaca.

Tomemos una muestra. El libro Historia del pensamiento económico de Murray Rothbard (con prólogo de Jesús Huerta de Soto) contiene una sanguinaria crítica a Adam Smith: "El problema no es simplemente que Smith no fuera el fundador de la economía. El problema es que no alumbró nada nuevo que fuese verdadero, y que todo lo que originó fue erróneo (…) Adam Smith fue un plagiario desvergonzado (…) Smith no solo no contribuyó en nada importante al pensamiento económico; más aún, su economía constituyó un grave deterioro en relación con sus predecesores". Según la afiebrada lectura libertaria, Smith terminó siendo "el fundador teórico de las doctrinas del socialismo del siglo XIX". Como se observa, viene de lejos lo de ver socialistas por todos lados.

Por supuesto, además de rechazar de cuajo su análisis del valor, Rothbard le reprocha haber apoyado la intervención del Estado donde éste solo puede hacer daño: leyes de navegación, educación, obras públicas, acuñación de moneda, registro de hipotecas, y muchas más. Para peor, "Smith defiende también una lista especialmente larga de impuestos, cada uno de los cuales interfiere en el mercado libre". En fin, para Rothbard, y para Huerta de Soto, La riqueza de las naciones representa "un desastre absoluto" y "un desvío trágico" que hace retroceder 100 años a la teoría económica y hasta lo denomina "el gran salto hacia atrás".

Examinemos ahora la actitud hacia Adam Smith de Javier Milei quien, como sabemos, llamó a uno de sus perros Murray en honor a Rothbard. No debe sorprender que al hablar de Smith haya seguido a pie juntillas el juicio de Rothbard y Huerta de Soto: "Adam Smith es un autor muy sobrevalorado. La realidad es que Adam Smith lo que hizo fue un gran salto atrás", "Smith no fue el padre de la economía, fue su sepulturero durante un siglo", "Adam Smith es un sistematizador, no un creador".

Por eso, quien haya escuchado la reciente exposición de Milei sobre Smith en el CCK se debe haber llevado una sorpresa o, más bien, un susto. En el homenaje, se deshizo en elogios hacia la obra y su autor. Sostuvo, contrariamente a lo que siempre dijo, que Smith "tiene más que ganado el título de padre de la economía", que es "el Gauss de la economía y estuvo 200 años adelantado a su época", lo consideró "Un gigante de la historia", "El Newton de la filosofía", "Un erudito" y a su libro "una obra indispensable".

Por supuesto, en su larga intervención, no se hizo referencia alguna a la contradicción entre lo que siempre opinó de Smith y su súbito fanatismo. No tengo mucho que agregar al respecto; es una muestra más de su comportamiento errático y acomodaticio, y de su "propensión natural" (diría Smith) a la mentira y a la estafa –esta vez, por suerte, sólo en el plano de la teoría–.

En una etapa como la actual, de cambio estructural en la economía mundial y de grandes interrogantes sobre el porvenir, la lectura de Adam Smith aporta claves siempre útiles para pensar sobre el desarrollo económico, la creación de riqueza y de empleo, la distribución y el papel del Estado. Nada de esto cabe en el diccionario ni en las preocupaciones de un libertario.

---

*Este artículo es parte de la serie conmemorativa por el 250° aniversario de la publicación de* La Riqueza de las Naciones *de Adam Smith, publicada en Clarín.*
