---
title: U4. La economía política. El pensamiento clásico. David Ricardo
subtitle: Historia del Pensamiento y del Análisis Económico
author: |
  | **Sebastián Freille**
  | sfreille@unc.edu.ar
  | Licenciatura en Economía
  | FCE-UNC
format:
  revealjs:
    slide-number: true
    chalkboard:
      buttons: false
    preview-links: auto
    css: ..\quarto.css
    width: 1500
    center-title-slide: true
    center: true
    tbl-cap-location: bottom	
    toc: true
    toc-depth: 1
    toc-title: Contenidos
    link-external-newwindow: true
---

# El corazón de la economía clásica {background="#43464B"}

## El sistema ricardiano

- Adam Smith no sólo estableció los fundamentos de la teoría clásica
  del valor y la primera teoría sobre crecimiento económico, sino que
  generó una curiosidad e interés inusitado por las cuestiones
  económicas
- David Ricardo, Thomas Malthus, James y John Stuart Mill, Jeremy
  Bentham y Nassau Senior fueron figuras realmente importantes de la
  escuela clásica inglesa que ciertamente vieron en la obra de Smith
  un oasis de curiosidad intelectual
  
## David Ricardo [1772-1823]

- Hijo de inmigrantes y agente de bolsa con una muy elemental
  educación comercial que sin embargo consiguió reunir una buena
  fortuna gracias a su sagacidad para las inversiones
- Fue tal vez el primer economista que logró articular un **sistema
  analítico general** del que derivaba **conclusiones fundamentales**
  a partir de unos **pocos principios básicos**

## David Ricardo [1772-1823] (cont.)

- El sistema de David Ricardo era un **monumento al proceso de
  razonamiento deductivo**. Consistía fundamentalmente en 3 (tres)
  principios básicos
  1. la teoría clásica de la renta
  2. el principio de la población de Malthus
  3. la doctrina del fondo de salarios

## David Ricardo [1772-1823]: la doctrina clásica de la renta

- La primera vez que se sugiere la existencia de rendimientos
  decrecientes es en un tratado de James Anderson, padre e inventor
  del arado escocés
- Uno de los elementos centrales que permitió aflorar esta discusión
  fue el papel preponderante de las denominadas *Leyes de Granos*
  durante las guerras napoleónicas
  - Napoleón trazó un embargo sobre puertos británicos --escasez de
    grano extranjero requirió de aumento de producción de grano en UK
- El costo de producción era más alto lo que siguió fue un fuerte
  aumento del principal alimento
  
## David Ricardo [1772-1823]: la doctrina clásica de la renta (cont.)

-
  



