---
title: U2. Desde los inicios hasta fines de la Edad Media 
subtitle: Historia del Pensamiento y del Análisis Económico
author: |
  | **Sebastián Freille**
  | sfreille@unc.edu.ar
  | Licenciatura en Economía
  | FCE-UNC
format:
  revealjs:
    slide-number: true
    chalkboard:
      buttons: false
    preview-links: auto
    css: ..\quarto.css
    width: 1500
    center-title-slide: true
    center: true
    tbl-cap-location: bottom	
    toc: true
    toc-depth: 1
    toc-title: Contenidos
    link-external-newwindow: true
---

# Características de las ideas antiguas sobre la economía {background="#43464B"}

## Aristóteles

- En *Politics*, Aristóteles discute la propiedad privada, el
  comunismo y la familia
  - sus argumentos aquí casi que podrían equipararse a los emitidos
    por liberales de clase media del siglo XIX
- La sociedad en que vivía Aristóteles respiraba un aire en que la
  esclavitud era *esencial*
  - pero en la que esta institución esencial se encontraba bajo
    fuertes críticas de los críticos y pensadores
- La esclavitud se había convertido en un problema -- a ello ofreció
  una explicación y justificación
  - la desigualdad *natural* de los hombres --por virtud de cualidad
    innata, algunos hombres destinados al sometimiento, otros a
    liderar

## Aristóteles (cont.)

- Planteó que había además causas no naturales e injustas de la
  esclavitud 
  - sometimiento a esclavitud indiscriminado de prisioners de guerra  
  
## Aristóteles (cont.)

- Los principios y discusiones económicas de Aristóteles se encuentran
  esencialmente en *Politics* Cap. I y en *Ethics* Cap. V
- Estuvo principalmente preocupado por lo *natural* y lo *justo* con
  el prismo de lo que el consideraba el ideal de una buena y virtuosa
  vida
- Basó su 'análisis económico' puramente a partir de necesidades
  (*wants*) y su satisfacción (*satisfactions*)
  - partió de la economía del hogar autosuficiente y de ahí derivó
    discusiones sobre la división del trabajo, trueque y dinero
- No hay ninguna teoría sobre distribución

## Aristóteles: valor

- Distinguió entre valor en uso y valor en cambio (intercambio) sino
  que intuyó que el segundo fenómeno deriva de alguna manera del
  primero
- Los escolásticos lograron avanzar más que El Filósofo en este tema,
  y pueden ser reconocidos como los que desarrollaron la teoría del
  precio
  - Aristóteles no ofreció ninguna teoría del valor de cambio (o del precio)
- Se ha sugerido que su falla en identificar esto fue haberse
  focalizado en el problema ético de la justicia en el intercambio
  --*justicia conmutativa*- lo cual dificultó enfocarse en el problema analítico
  
  
## Aristóteles: valor

- Pero no es cierto esto $\longrightarrow$ la preocupación por la
  ética de la fijación de precios es uno de los principales motivos
  que un hombre puede tener para analizar los mecanismos de mercado
- Consideró sin embargo el caso del monopolio
  - lo definió como la posición en un mercado de un Sólo Vendedor y lo
    condenó como injusto
- Su planteo de buscar un elemento de justicia en la determinación de
  precios lo llevó a exponer el principio de equivalencia entre lo que
  el hombre da y recibe. 
  
  
## Aristóteles: valor

- Esencialmente, dado que en un trueque ambas partes deben
  necesariamente ganar del mismo --ganancia entendida en el sentido de
  estar mejor luego que antes del intercambio
	  - no podría haber equivalencia entre los valores 'subjetivos' o
        de utilidad de los bienes intercambiados; o entre los bienes
        intercambiados y el dinero recibido. 
- En este sentido, Aristóteles debe haber pensado en algun *valor
  objetivo (absoluto) de las cosas*, algo intrínseco e inherente que
  es independiente de las circunstancias y/o de las valuaciones
  humanas
  
## Aristóteles: valor

- Sin embargo, la falla en explicarlo no implica falla en lograr
  reconocerlo como un hecho --más razonable pensar que Aristóteles
  pensó a los valores de cambio del mercado como expresados en
  términos de dinero mas que en términos de alguna sustancia de valor 
- Es decir, aceptó los precios de los bienes observados en el mercado
  como estandares de su justicia conmutativa pero...
  - condenó los precios de monopolio
- Se puede intuir que distinguió entre precios que los individuos
  observaban como dados --precios competitivos- y precios que algún
  individuo o grupo había fijado para su propio beneficio --precios
  monopolicos
  
## Aristóteles: valor

- Esto lo hacía pasible a aceptar cualquier transacción que sucediera
  a los *precios competitivos* como *justa* --que fue basicamente lo
  que los escolásticos aceptaron y se conformaron explícitamente. 
- De alguna manera, su concepto del valor justo de una mercancía es
  'objetivo'
  - pero sólo en el sentido de que ningún individuo puede alterarlo
    producto de su acción 
- Extendió estos valores justos a nivel individual a valores justos a
  nivel social --es decir esos valores representaban lo que la
  comunidad consideraba el valor justo a nivel agregado
  
  
## Aristóteles: valor

> La justicia conmutativa sera servida en cada acto de intercambio. Si
> A cambia zapatos por rodajas de pan de B, la justicia aristotelica
> requiere que los zapatos igualen a las rodajas de pan cuando ambas
> son multiplicados por sus precios competitivos normales; si A vende
> sus zapatos a B por dinero, la misma regla debera ser observada para
> saber cuanto dinero recibir. 
  

## Aristóteles: dinero

- La existencia misma de cualquier sociedad no comunista involucra el
  intercambio de bienes y servicios
- Inicialmente esto se da a través de trueque; pero esto no siempre es
  posible, o tiene un limite
- Esto implicará que eventualmente los intercambios se realizarán a
  través de alguna commodity como *medio de cambio*
- Sugirio que algunas commodities cumplian mejor ese rol --metales
- Asimismo, por el requerimiento de su regla de equivalencia en el
  intercambio, se seguía que esta commodity tambien sería usada como
  *medida de valor*

## Aristóteles: dinero

- Y finalmente reconoció, al menos implícitamente, su rol como
  *depósito de valor*
  - esto fue un gran antecedente casi 2500 años antes de las
    discusiones en siglo XIX
- Dos proposiciones en su teoría:
  1. Adicionalmente a cualquier otra función, el dinero tenía como
     función fundamental el de servir como medio de cambio
  2. En orden a servir como medio de cambio en los mercados de bienes,
     el dinero también debía ser una de esas commodities --es decir,
     existía un mercado de dinero
- En otras palabras, el dinero debía tener valor en cambio
  --adicionalmente e independiente de su rol como medio de cambio
  
## Aristóteles: dinero

- La commodity 'dinero' va por peso y por calidad como las otras
  commodities 
  - teoría metalista del dinero
- 
  
