---
title: Finanzas Públicas
subtitle: Finanzas Públicas [Cat. Barraud]
---

## Bienvenida 

- Este es un sitio de **clases interactivas de la materia Finanzas
Públicas (cátedra Barraud)** del tercer año de la carrera de Contador
Público de la Facultad de Ciencias Económicas (FCE) de la Universidad
Nacional de Córdoba (UNC).

- Esta versión corresponde al dictado del **Curso de Verano 2026**

---

## Aspectos organizativos

- En esta sección presentaremos los principales aspectos generales y organizativos de la materia. 

---

## Equipo de cátedra

- Profesor: BARRAUD, Ariel
  - PhD in Applied Economics (University of Antwerpen)
  - Lic. en Economía (UNC)
- Profesor: FREILLE, Sebastián
  - PhD en Economía (University of Nottingham)
  - Lic. en Economía (UNC)
- Profesor Ayudante: GRIÓN, Néstor
  - Lic en Economía (UNC) / Candidato Doctoral (FCE-UNC)

---

## Clases y dictado

- El curso se dicta usando la propuesta de **Ciclo Formato Combinado
(CFC)** involucrando una combinación de estrategias a saber: 

1. **Clases teóricas y prácticas sincrónicas híbridas** (dictado presencial y
   transmisión por videoconferencia) y **sincrónicas virtuales** (dictado virtual y transmisión por videoconferencia)
2. **Actividades a distancia** en aula virtual
3. **Horas de consulta semanales sincrónicos virtuales** (transmisión por videoconferencia)

---

## Clases y dictado (cont.)

- Los **horarios de las clases** semanales serán:

1. Clases teóricas: lunes a viernes de 17:00 a 21:00 
2. Clases prácticas: días seleccionados de 19:00 a 21:00 (consultar
   cronograma adjunto)

---

## Objetivo general

> Desarrollar el **estudio de la actividad económica y financiera del sector público en la economía** y brindar a los alumnos **herramientas teórico-analíticas y empíricas** para comprender la naturaleza, el funcionamiento y los efectos de la actividad del sector público en el conjunto de la economía.

---

## Objetivos específicos

- Introducir y explicitar las **diferencias entre decisiones privadas y decisiones públicas**
- Establecer y desarrollar las **diferentes metodologías y enfoques** de abordaje
- Promover el **abordaje sistemático** de la actividad del sector público focalizando en los efectos sobre el resto de la economia
- Estimular en los alumos el **espíritu reflexivo y crítico** en relación a las decisiones y evaluaciones de política pública

---

## Programa de la materia

1. U1. La economía del sector público: Introducción, conceptos y alcance
2. U2. Las decisiones colectivas: Agregación de preferencias y decisiones sociales
3. U3. El gasto público. El presupuesto público
4. U4. Los recursos del sector público
5. U5. Impuestos a los ingresos
6. U6. Impuestos a los consumos
7. U7. Impuestos a la riqueza y otros impuestos
8. U8. Sostenibilidad fiscal: déficit público, endeudamiento y emisión monetaria
9. U9. Federalismo fiscal y relaciones financieras inter-gubernamentales

---

## Bibliografía y textos

- La cátedra no sigue un texto único. Pero hay 2 (dos) libros principales:
    1. Stiglitz, J.E. (2000). [*La economía del sector público*](https://www.amazon.com/-/es/Joseph-Stiglitz/dp/8495348055). (3ra edición). Barcelona: Antoni Bosch
    2. Rosen, H. (2008). [*Hacienda pública*](https://www.amazon.com/-/es/Harvey-S-Rosen/dp/8448156625/). Madrid: McGraw-Hill
- Libros complementarios
    1. Musgrave, R., and Musgrave, P. (1992). [*Hacienda pública teórica y aplicada*](https://www.amazon.com/-/es/Richard-Musgrave/dp/8476157568/). (5ta edición). Madrid: McGraw-Hill
    2. Garriga, M., y Rosales, W. (2013). [*Finanzas públicas en la práctica. Selección de casos y aplicaciones*](http://sedici.unlp.edu.ar/bitstream/handle/10915/30300/Documento_completo__.pdf?sequence=3). Buenos Aires: Editorial Dunken

---

## Evaluación

- Se obtiene la **regularidad aprobando 2 (dos) de 3 (tres)
  parciales**. Si aprueba los 2 (dos) primeros no rinde el
  restante. Todos los parciales serán **presenciales físicos**
-  **Se aprueba la materia** (1) rindiendo y aprobando un examen en condición de regular; o (2) rindiendo y aprobando dos exámenes, uno en condición de libre y otro en condición de regular.
- En todos los casos **se aprueba con 50 puntos sobre 100**, sin excepciones
-  **No hay promoción** directa ni indirecta

---

## Fechas importantes

- El primer parcial será el **13-FEB-2026** de 17:00 a 19:00
    - Incluye U1 a U4 inclusive. Notas y muestra: 
- El segundo parcial es el **25-FEB-2026** de 17:00 a 19:00
    - Incluye U5 a U9 inclusive. Notas y muestra: 
- El recuperatorio será el **02-MAR-2026** de 17:00 a 19:00
    - Se recuperan los temas del parcial reprobado/ausente. Notas,
      muestra y cierre de condiciones el mismo día. 

---

## Puntos de encuentro

1. Aula virtual de la materia
    - Link directo: [Aula virtual Finanzas Públicas
      (Cat. Barraud)](https://eco.aulavirtual.unc.edu.ar/course/view.php?id=485)
2. Salas Google Meet
    - Freille: [Sala Google
      Meet](https://meet.google.com/pyx-spym-hxd)
3. Mail y otros
    - Se responden mensajes en foros a lo largo de la semana (no en el día)
    - No usamos grupos de whatsapp y/u otro

---

## Resumiendo

1. Sugerencia de leer filminas y bibliografía antes de clases teóricas
   y (fundamentalmente) de clases prácticas
2. **Dificultad media/alta** pero nuestra filosofía es:
    1. Explicamos los temas del programa 
    2. Evaluamos sólo lo que explicamos
    3. Explicamos cómo evaluamos/corregimos
    4. Mostramos evaluaciones/damos devoluciones
3. Se **promueve y estimula debates actuales** pero el foco es en la descripción y análisis y no en juicios de valor y opiniones
