---
title: Economía Política
subtitle: Presentación de la materia
author: |
  | **Sebastián Freille**
  | sfreille@unc.edu.ar
  | Licenciatura en Economía
  | FCE-UNC

output:
  revealjs::revealjs_presentation:
    center: true
    highlight: pygments
    transition: slide
    css: ..\style.css
header-includes:
  - \usepackage{amsmath}
  - \usepackage{tcolorbox}
  - \newtcolorbox{myquote}{colback=cyan!35!white, colframe=cyan!85!black}
  - \renewenvironment{quote}{\begin{myquote}}{\end{myquote}}
---

# **Economía política**

- Fundamentación y objetivos
- Clases, materiales y dictado
- Metodología de evaluación y aprobación
- Programa abreviado

---

# **Fundamentación y objetivos**

## Fundamentación

> En las últimas décadas, se ha producido una convergencia gradual a un significativo cuerpo de ideas teóricas y aplicadas por parte de varias tradiciones disciplinares que estudian diferentes aspectos del comportamiento del gobierno, los múltiples actores que componen el mismo y las interacciones entre los fenómenos económicos y los fenómenos políticos. Entre ellas la escuela de la public choice en Economía, la escuela de la rational choice en Ciencia Política y la escuela   de la nueva economía institucional, han originado un frondoso cuerpo de temas, modelos y evidencias que tienen en general un núcleo común: el uso de herramientas analíticas y formales para capturar los aspectos centrales de los fenómenos estudiados usando un enfoque mayoritariamente positivo.

## Objetivos

> El objetivo de la materia es el estudio y análisis de las interacciones entre la economía y la política utilizando un enfoque positivo. En un sentido amplio, estudia tanto los fundamentos políticos de las acciones económicas - la forma en que la estructura, instituciones e incentivos políticos afectan las acciones y resultados del mercado-- como también los fundamentos económicos de las acciones políticas - la forma en que la estructura, instituciones e incentivos económicos afectan las acciones y resultados políticos. El enfoque del curso es teórico-aplicado.

# **Clases, materiales y dictado**

## Clases

- Los **días y horarios de las clases presenciales** semanales serán:
  - Lunes de 15:00 a 17:00 [Freille]
  - Martes de 15:00 a 17:00 [Freille]
- Habrá **transmisión en vivo** a través del siguiente link: https://meet.google.com/cbd-ihjm-xyq  

## Materiales

- El programa de la materia contiene las unidades temáticas, contenidos y bibliografía
- No hay un libro de texto único ni sugerido para el desarrollo de la materia. Hay 3 a 5 libros importantes sobre los que se trabajan varios temas y una gran cantidad de papers y material de aplicación
- La cátedra ha dispuesta una web dedicada: https://sfreille.github.io/teaching/epol
- El material estará disponible en la web a medida que se vaya trabajando

## Libros de texto

1. Fergusson, L., & Querubín, P. (2018). Economía política de la política económica (pp. 413-413). Universidad de los Andes.
2. Persson, T., & Tabellini, G. (2002). Political economics: explaining economic policy. MIT press.
3. Shepsle, K. A., & Serra, G. (2016). Analizar la política: comportamiento, instituciones y racionalidad. CIDE.

## Dictado y asistencia

- Todas las clases agendadas serán dictadas de manera presencial con transmición en vivo para aquellos estudiantes que no puedan sumarse
- Se requerirá cumplir con un porcentaje de asistencia mayor o igual al 50\%como condición necesaria para la regularidad
- Las clases serán de tipo magistral, los temas presentados por el profesor promoviendo participación de estudiantes
- Las clases durarán 100 minutos en total. Se prevee la posibilidad de hacer algun break corto durante las mismas. 

# **Metodología de evaluación y aprobación**

## Evaluacion y aprobación

- Se obtiene la **regularidad aprobando 2 (dos) parciales y teniendo al menos 50% de asistencia entre clases presenciales y remotas**. Se puede recuperar hasta un sólo parcial, por aplazo o ausencia. Los parciales serán **presenciales físicos** mientras que el recuperatorio será **presencial remoto en aula virtual**
- **Se aprueba la materia** (1) rindiendo y aprobando un examen en condición de regular; o (2) rindiendo y aprobando dos exámenes, uno en condición de libre y otro en condición de regular.
- En todos los casos **se aprueba con 50 puntos sobre 100**, sin excepciones
- **No hay promoción** directa ni indirecta

## Fechas importantes

- A decidir

# **Programa abreviado**

## Programa abreviado

1. Es la política, estúpido! Introducción a la economía política
2. En la vida hay que elegir: ¿cómo eligen las sociedades?
3. La Democracia es el peor sistema de gobierno (con excepción de todas las demás)
4. No taxation without representation: Partidos, votantes y competencia electoral
5. Estos son mis principios. Si no le gu$tan, tengo otros: Influencia, dinero y grupos de interés

---

## Programa abreviado (cont.)

6. El que depositó dólares, recibirá dólares: Derechos de propiedad, persistencia institucional y cambio institucional endógeno
7. Hay que dejar de robar por dos años: Corrupción y desgobierno
8. I love the smell of napalm in the morning. Conflicto, violencia política y consecuencias sociales y políticas
9. Bad informeishon: Información, medios de comunicación y efectos políticos y electorales
10. Dios está en todos lados pero atiende en Buenos Aires: economía política del federalismo y la descentralización